version: '3.7'

services:
  # user_service:
  #   build:
  #     context: ./user_service
  #   ports:
  #     - "8001:8001"
      
  #   environment:
  #     DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
  #     DJANGO_DEBUG: "True"
  #     DB_NAME: "defaultdb"
  #     DB_USER: "avnadmin"
  #     DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
  #     DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
  #     DB_PORT: "12783"
  #     DB_SCHEMA: "user_schema"
  #   networks:
  #     - shared_network   
  
  product_service:
    build:
      context: ./product_service
    ports:
      - "8002:8002"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "product_schema"
      AUTH_SERVICE_URL: "https://auth-service-4r29.onrender.com/api/users"
    
    networks:
      - shared_network   

  order_service:
    build:
      context: ./order_service
    ports:
      - "8003:8003"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "order_schema"
      AUTH_SERVICE_URL: "http://e_commerce_app_django-user_service-1:8001/api/users"
      ALLOWED_HOSTS: "payment_service,localhost,127.0.0.1,[::1]"
    networks:
      - shared_network   

  payment_service:
    build:
      context: ./payment_service
    ports:
      - "8004:8004"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "payment_schema"
      AUTH_SERVICE_URL: "http://e_commerce_app_django-user_service-1:8001/api/users"
      ALLOWED_HOSTS: "payment_service,localhost,127.0.0.1,[::1]"
    networks:
      - shared_network   

  cart_service:
    build:
      context: ./cart_service
    ports:
      - "8005:8005"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "cart_schema"
      AUTH_SERVICE_URL: "http://e_commerce_app_django-user_service-1:8001/api/users"
    networks:
      - shared_network   


  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8006:8006"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "notification_schema"
      AUTH_SERVICE_URL: "http://e_commerce_app_django-user_service-1:8001/api/users"


    networks:
      - shared_network  
networks:
  shared_network:
    external: true 