version: '3.7'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
      
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "user_schema"

  
  product_service:
    build:
      context: ./product_service
    ports:
      - "8002:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "product_schema"


  order_service:
    build:
      context: ./order_service
    ports:
      - "8003:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "order_schema"


  payment_service:
    build:
      context: ./payment_service
    ports:
      - "8004:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "payment_schema"


  cart_service:
    build:
      context: ./cart_service
    ports:
      - "8005:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "cart_schema"


  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8006:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "notification_schema"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A product_service worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A product_service beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0     