# Generated by Django 5.0.7 on 2024-07-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.IntegerField(default=1),
        ),
    ]
