# Generated by Django 5.0.7 on 2024-07-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauditlog',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
