version: '3.7'

services:
  product_service:
    build:
      context: .
    container_name: product_service  
    ports:
      - "8002:8000"
    environment:
      DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
      DJANGO_DEBUG: "True"
      DB_NAME: "defaultdb"
      DB_USER: "avnadmin"
      DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
      DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
      DB_PORT: "12783"
      DB_SCHEMA: "product_schema"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      AUTH_SERVICE_URL: "http://user_service:8001/api/users"
    networks:
      - shared_network    

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

  # celery_worker:
  #   build: .
  #   container_name: celery_worker
  #   command: celery -A product_service worker --loglevel=info
  #   depends_on:
  #     - redis
  #   environment:
  #     DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
  #     DJANGO_DEBUG: "True"
  #     DB_NAME: "defaultdb"
  #     DB_USER: "avnadmin"
  #     DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
  #     DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
  #     DB_PORT: "12783"
  #     DB_SCHEMA: "product_schema"
  #     CELERY_BROKER_URL: "redis://redis:6379/0"
  #     CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  # celery_beat:
  #   build: .
  #   container_name: celery_beat
  #   command: celery -A product_service beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   depends_on:
  #     - redis
  #   environment:
  #     DJANGO_SECRET_KEY: "django-insecure-l7x#+v738270%6i&r3*eekfjtqi)ny8oe(m3oziu5rlk3=y^z("
  #     DJANGO_DEBUG: "True"
  #     DB_NAME: "defaultdb"
  #     DB_USER: "avnadmin"
  #     DB_PASSWORD: "AVNS_YvmZwdl9kb18WKUmnHK"
  #     DB_HOST: "pg-1ea7758e-pallavidapriya75-97f0.c.aivencloud.com" 
  #     DB_PORT: "12783"
  #     DB_SCHEMA: "product_schema"
  #     CELERY_BROKER_URL: "redis://redis:6379/0"
  #     CELERY_RESULT_BACKEND: "redis://redis:6379/0"  

networks:
  shared_network:
    external: true  